language: node_js
before_install:
  - npm -g install npm@latest
matrix:
  include:

    # Only run tests in Sauce Labs for 0.12
    # to avoid unnecessary running VMs
    - node_js: "0.12"
      env: SAUCE_LABS=true
      script:
        - npm test
        - karma start

    - node_js: "0.11"
      script:
        - npm test
    - node_js: "0.10"
      script:
        - npm test
notifications:
  email: false
